when@dev:
    web_profiler:
        toolbar: true

    framework:
        profiler:
            # collect_serializer_data removed for PHP 8.0 compatibility/older Symfony version

when@test:
    framework:
        profiler: { collect: false }
